query getData {
	heroCollection(order: name_ASC) {
		items {
			sys {
				id
			}
			name
			image {
				url
			}
			rarity
			role {
				sys {
					id
				}
				name
			}
			element {
				sys {
					id
				}
				name
			}
			chainAilmentStart {
				sys {
					id
				}
				name
				isAny
			}
			chainAilmentEnd {
				sys {
					id
				}
				name
			}
			partyBuff {
				sys {
					id
				}
				name
			}
			partyBuffValue
			partyBuff2 {
				sys {
					id
				}
				name
			}
			partyBuffValue2
			defaultWeapon {
				sys {
					id
				}
			}
			weaponCategoriesCollection(limit: 10) {
				items {
					sys {
						id
					}
				}
			}
		}
	}
	heroRoleCollection(limit: 4) {
		items {
			sys {
				id
			}
			name
		}
	}
	weaponCollection(order: name_ASC) {
		items {
			sys {
				id
			}
			name
			element {
				sys {
					id
				}
				name
			}
			ailment {
				sys {
					id
				}
				name
			}
			category {
				sys {
					id
				}
				name
			}
			image {
				url(transform: { height: 75, width: 75 })
			}
		}
	}
	weaponCategoryCollection(limit: 10) {
		items {
			sys {
				id
			}
			name
		}
	}
	elementCollection(limit: 10) {
		items {
			sys {
				id
			}
			name
		}
	}
	ailmentCollection(limit: 4) {
		items {
			sys {
				id
			}
			name
			image {
				url(transform: { width: 30, height: 30 })
			}
			isAny
		}
	}
	heroPartyBuffCollection(limit: 30) {
		items {
			sys {
				id
			}
			name
		}
	}
}
