query getHeros {
	heroCollection {
		items {
			name
			rarity
			role {
				name
			}
			element {
				name
			}
			image {
				url
			}
			chainAilmentStart {
				name
			}
			chainAilmentEnd {
				name
			}
			defaultWeapon {
				name
			}
		}
	}
}
